"""Editing of masks, or replacement of automasks by edited masks"""

import os
import logging

from tqdm import tqdm
import numpy as np
import dbdicom as db
from miblab import pipe

from totseg.utils.total_segmentator_class_maps import class_map
from totseg.utils import data, edit



PIPELINE = 'totseg'

def run(build, logfile, organ=None, plane='coronal'):

    if not organ:
        raise ValueError('Please specify an organ to edit')

    task='total_mr'

    datapath = os.path.join(build, 'dixon', 'stage_5_clean_dixon_data')
    maskpath = os.path.join(build, 'totseg', 'stage_1_segment')
    editpath = os.path.join(build, 'totseg', 'stage_4_edit', organ)
    os.makedirs(editpath, exist_ok=True)

    # Controls
    group = "Controls"
    sitedatapath = os.path.join(datapath, group) 
    sitemaskpath = os.path.join(maskpath, group)
    siteeditpath = os.path.join(editpath, group)

    run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ, plane)

    group = "Patients"
    for site in ['Exeter', 'Bari', 'Leeds', 'Bordeaux', 'Turku', 'Sheffield']:
        sitedatapath = os.path.join(datapath, group, site) 
        sitemaskpath = os.path.join(maskpath, group, site)
        siteeditpath = os.path.join(editpath, group, site)

        run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ, plane)



def run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ, plane):

    # List of selected dixon series
    record = data.dixon_record()

    # Invert class map
    label_map = {v: k for k, v in class_map[task].items()}

    # Loop over the autogenerated masks
    for mask_series in tqdm(db.series(sitemaskpath)):

        # Skip if not the correct task
        if mask_series[-1][0] != task:
            continue

        # Patient and output study
        patient = mask_series[1]
        study = mask_series[2][0]

        # Skip if the edited masks already exist
        edited_mask_study = [siteeditpath, patient, (study, 0)]
        edited_mask_series = edited_mask_study + [(f"{organ}_edited", 0)]
        if edited_mask_series in db.series(edited_mask_study):
            continue

        # Get the out-phase sequence
        sequence = data.dixon_series_desc(record, patient, study)
        series_op = [sitedatapath, patient, study, sequence + '_out_phase']
        op = db.volume(series_op)

        # Get the auto-mask
        auto_label_series = [sitemaskpath, patient, study, task]
        auto_label = db.volume(auto_label_series)

        # Edit the mask and save
        transp = {
            'coronal': (0,1,2),
            'sagittal': (2,1,0),
            'axial': (0,2,1),
        }[plane]
        try:
            oparr = op.values.transpose(transp)
            lblarr = auto_label.values.transpose(transp)
            edited_label = edit.edit_mask_with_napari(oparr, lblarr, default_label=label_map[organ])
            edited_label = edited_label.transpose(transp)
        except Exception as e:
            logging.error(f"{patient} {study} error editing mask: {e}")
        else:
            edited_mask = edited_label == label_map[organ]
            vol = (edited_mask.astype(np.int16), op.affine)
            db.write_volume(vol, edited_mask_series, ref=series_op)
            # if not np.array_equal(auto_mask.values, vol[0]):
            #   db.write_volume(vol, edited_mask_series, ref=series_op)


if __name__=='__main__':

    BUILD = r"C:\Users\md1spsx\Documents\Data\iBEAt_Build"
    kwargs = {
        "organ": {
            'type': str, 
            'default': None, 
            'help': 'Organ',
        },
        "plane": {
            'type': str, 
            'default': 'coronal', 
            'help': 'Plane',
        }
    }
    pipe.run_stage(run, BUILD, PIPELINE, __file__, **kwargs)

