"""Editing of masks, or replacement of automasks by edited masks"""

import os
import logging
import numpy as np
import dbdicom as db
from miblab import pipe

from utils.total_segmentator_class_maps import class_map
from utils import data, edit



PIPELINE = 'totseg'

def run(build, logfile):

    task='total_mr'
    organ='aorta'

    datapath = os.path.join(build, 'dixon', 'stage_5_clean_dixon_data')
    maskpath = os.path.join(build, 'totseg', 'stage_1_segment')
    editpath = os.path.join(build, 'totseg', 'stage_4_edit')
    os.makedirs(editpath, exist_ok=True)

    # Controls
    group = "Controls"
    sitedatapath = os.path.join(datapath, group) 
    sitemaskpath = os.path.join(maskpath, group)
    siteeditpath = os.path.join(editpath, group)

    run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ)

    group = "Patients"
    for site in ['Exeter', 'Bari', 'Leeds', 'Bordeaux', 'Turku', 'Sheffield']:
        sitedatapath = os.path.join(datapath, group, site) 
        sitemaskpath = os.path.join(maskpath, group, site)
        siteeditpath = os.path.join(editpath, group, site)

        run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ)



def run_site(sitedatapath, sitemaskpath, siteeditpath, task, organ):

    # List of selected dixon series
    record = data.dixon_record()

    # Invert class map
    label_map = {v: k for k, v in class_map[task].items()}

    # Loop over the autogenerated masks
    for mask_series in db.series(sitemaskpath):

        # Skip if not the correct task
        if mask_series[-1][0] != task:
            continue

        # Patient and output study
        patient = mask_series[1]
        study = mask_series[2][0]

        # Skip if the edited masks already exist
        edited_mask_study = [siteeditpath, patient, (study, 0)]
        edited_mask_series = edited_mask_study + [(f"{organ}_edited", 0)]
        if edited_mask_series in db.series(edited_mask_study):
            continue

        # Get the out-phase sequence
        sequence = data.dixon_series_desc(record, patient, study)
        series_op = [sitedatapath, patient, study, sequence + '_out_phase']
        op = db.volume(series_op)

        # Get the auto-mask
        auto_label_series = [sitemaskpath, patient, study, task]
        auto_label = db.volume(auto_label_series)

        # Edit the mask and save
        try:
            edited_label = edit.edit_mask_with_napari(op.values, auto_label.values, default_label=label_map[organ])
        except Exception as e:
            logging.error(f"{patient} {study} error editing mask: {e}")
        else:
            edited_mask = edited_label == label_map[organ]
            vol = (edited_mask.astype(np.int16), op.affine)
            db.write_volume(vol, edited_mask_series, ref=series_op)
            # if not np.array_equal(auto_mask.values, vol[0]):
            #   db.write_volume(vol, edited_mask_series, ref=series_op)


if __name__=='__main__':

    BUILD = r"C:\Users\md1spsx\Documents\Data\iBEAt_Build"
    # pipe.run_client_stage(run, BUILD, PIPELINE, __file__, min_ram_per_worker=16)
    pipe.run_stage(run, BUILD, PIPELINE, __file__)

